_global_:
  missing_value_strategy_numeric: "median"
  missing_value_strategy_categorical: "mode"
  n_estimators: 100
  max_depth: 10
  additional_features_to_drop: []
  min_accuracy: 0.35
  min_f1: 0.30

baseline:
  description: "Random Forest Baseline"

