# Training settings
data_url_raw: "./data/raw/WA_Fn-UseC_-HR-Employee-Attrition.CSV"
data_url_processed: "./data/processed/WA_Fn-UseC_-HR-Employee-Attrition.CSV"
target: "Attrition"
test_size: 0.2
random_state: 75
n_estimators: 100
max_depth: 10
columns_to_drop:
  - "EmployeeNumber"
numeric_columns:
  - "Age"
  - "DailyRate"
  - "DistanceFromHome"
  - "EmployeeCount"
  - "HourlyRate"
  - "MonthlyIncome"
  - "MonthlyRate"
  - "NumCompaniesWorked"
  - "PercentSalaryHike"
  - "StandardHours"
  - "TotalWorkingYears"
  - "TrainingTimesLastYear"
  - "YearsAtCompany"
  - "YearsInCurrentRole"
  - "YearsSinceLastPromotion"
  - "YearsWithCurrManager"
categorical_columns:
  - "BusinessTravel"
  - "Department"
  - "Education"
  - "EducationField"
  - "EnvironmentSatisfaction"
  - "Gender"
  - "JobInvolvement"
  - "JobLevel"
  - "JobRole"
  - "JobSatisfaction"
  - "MaritalStatus"
  - "Over18"
  - "OverTime"
  - "PerformanceRating"
  - "RelationshipSatisfaction"
  - "StockOptionLevel"
  - "WorkLifeBalance"
min_accuracy: 0.35
min_f1: 0.30